export const botOptionsAndReplies = new Map([
	["hola", "hola chavales"],
	["sergi es noob", "efectivament"],
	["vamos valorant", "venga va"],
	["quiero un chupito", "preparando una mulata cachonda!"],
	["quiero una absenta", "Xavi... no tuviste suficiente?"],
	["josep no es un troll", "NICE MEME"],
	["toni vienes valorant?", "voy a estudiar"],
	["que te parece toni?", "INJUGABLE"],
	["quiero una pizza", "marchando una diabla sin guindilla"],
	["report", "Diego estás reportado 📝"],
	["rocket?", "🏎️🚀⚽"],
	["vamos tft?", "voy yord... voy trainers"],
	["me voy a dormir", "a tu puta casa"],
	["gente que cae", "con las gafas en la riñonera"],
])
